language: ruby
rvm:
  - 2.1.5
  - 2.3.0
  - 2.2.4
bundler_args: --jobs=2
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - gem install rack -v '2.0.1'
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
gemfile:
  # - gemfiles/4.1.gemfile
  # - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
notifications:
  email: false
